### ISSUE TITLE
Any chance to have it upstreamed?

### ISSUE THREAD

**Issue by peterhoeg** [krzysztof-magosa/flycheck-yamllint#1]
Works great here, would be fantastic to have it part of flycheck upstream.

**Comment by krzysztof-magosa** [comment]
Hi @peterhoeg.
I'm not using Emacs too much these days (switched to Vim) but I've found 10 minutes to open PR to original Flycheck project. We will see if they accept it.

Kind Regards,
KM.

PR: https://github.com/flycheck/flycheck/pull/1640

**Comment by krzysztof-magosa** [comment]
Upstreamed successfully.
Thanks for your interest in my project,
KM.

**Comment by peterhoeg** [comment]
Thanks!!
